// In-app help for V3: what every non-obvious number, colour, line and
// button means. Edit wording here; the Help panel only renders it.
//
// Each section: { id, title, intro?, items: [{ term, body, key? }] }
// `key` draws a small visual sample next to the term:
//   { swatch: css-background }            a coloured box
//   { line: color, dash?: 'dashed'|'dotted', width? }
//   { dot: color }                        a chart marker
//   { bar: color, opacity? }              a demand bar
//   { shift: color, opacity }             a shift block
// Sections with an `id` can be opened directly by the small ? buttons.

import { STATUS_SWATCH } from '../components/coverageStyles'

export const HELP_SECTIONS = [
  {
    id: 'start',
    title: 'Start here',
    intro: 'This tool compares staffing against how many patients historically start with each area\'s team each hour, area by area, and helps you try out different schedules.',
    items: [
      { term: 'The core idea', body: 'For every area and hour, the tool compares how many patients typically start with the area\'s team (demand) with how many patients per hour the scheduled staff could handle under the assumed work rates on the sliders (modeled capacity). Modeled capacity below demand = the area is short that hour, in the model.' },
      { term: 'Layout', body: 'Top bar: tools. Below it: day tabs and summary numbers. Left: the day\'s schedule as a timeline, with a coverage bar and the week heatmap underneath. Right: the demand-vs-capacity chart for the selected area.' },
      { term: 'Nothing is saved automatically', body: 'Edits change your working copy in this browser session. Use Save scenario to keep a version, Export to download it, or Reset day to go back to the loaded schedule. Undo (⌘Z / Ctrl+Z) works for every change.' },
      { term: 'Areas are separate', body: 'Main, Fast Track and ERU each have their own demand and staff. Spare capacity in one area never covers a shortfall in another — this matters in the combined views (Main + ERU, Whole ED).' },
      { term: 'These are estimates', body: 'Capacity comes from assumed throughput numbers (see Key terms and Model assumptions). Modeled capacity is not observed throughput, unmet demand is not a wait time, and no result is a clinical staffing requirement. Treat every number as decision support to discuss.' },
      { term: 'Quick tour', body: '1) Pick an area tab on the chart. 2) Look for red on the coverage bar and heatmap. 3) Drag or click shifts to adjust. 4) Watch the chart and "Coverage issues" update. 5) Save the result as a scenario to compare.' },
      { term: 'Opening this help', body: 'Click ❓ Help in the top bar, press the ? key, or click any small ? next to a part of the screen to jump straight to its explanation.' },
    ],
  },
  {
    id: 'glossary',
    title: 'Key terms',
    items: [
      { term: 'PPH (patients per hour)', body: 'The unit used everywhere: how many patients start with a team per hour (demand), or how many a clinician or team can handle per hour (capacity).' },
      { term: 'Demand', body: 'Historical patients per hour for each area and day of the week, counted by the hour they were roomed with that area\'s team (not arrival time), averaged over every date in the data (a date with no patients for an area counts as zero).' },
      { term: 'Demand target — Mean / p50 / p75 / p90', body: 'Which version of historical demand to plan against. Mean = the average day. p50 = a typical (median) day. p75 / p90 = busier days: demand at that hour is at or below this on 75% / 90% of days. Percentiles are worked out hour by hour, so a "p90 day" strings together each hour\'s busy value and is busier than any typical single day; combined scopes add the areas\' percentiles (a slight overstatement). If a weekday has no percentile data the all-days percentile is used, then the mean. The buttons are greyed out only when no percentile data exists.' },
      { term: 'Capacity (modeled)', body: 'Patients per hour the scheduled staff could handle under the assumed rates, calculated per team and added up for the area. It is not how many patients staff actually saw.' },
      { term: 'Supervision ceiling (attending PPH)', body: 'The most patients per hour one attending can be responsible for, including patients seen by the residents/PAs they supervise. A team can never exceed this, however many residents it has. Defaults: Main 2.1, Fast Track 3.5, ERU 0.8.' },
      { term: 'Solo throughput', body: 'Patients per hour an attending sees personally when working alone. A team\'s capacity = the smaller of (ceiling) and (solo throughput + residents/PAs), so residents/PAs lift an attending up toward the ceiling but not past it.' },
      { term: 'Resident / PA PPH', body: 'Patients per hour each resident (by level: PGY-1 to PGY-4, Off-Service) or PA adds under supervision. Residents and supervised PAs count for nothing when no attending is on their team at that hour (the one exception: Fast Track PAs\' solo rate, below).' },
      { term: 'Fast Track PA (solo / with attending)', body: 'Fast Track PAs see patients on their own (solo rate) even with no attending on, plus a separate rate for patients co-managed with an attending. Solo PA capacity is added on top of the ceiling.' },
      { term: 'Team', body: 'One attending\'s group with its residents/PAs (e.g. Green, Red, Blue in Main). Capacity is calculated team by team; residents on one team never help another team\'s attending.' },
      { term: 'Area and scope', body: 'An area is Main, Fast Track or ERU. A scope is what you are looking at: one area, Main + ERU, or Whole ED. Combined scopes add the areas together but always keep each area\'s own result visible.' },
      { term: 'Baseline vs proposed', body: 'Baseline = the schedule as loaded from the database. Proposed = your current edited version. "vs baseline" numbers show the difference.' },
      { term: 'Short (deficit)', body: 'An hour where demand is higher than modeled capacity. On screen, a shortfall under 0.05 PPH (which would read "0.0") is shown as covered everywhere — heatmaps, coverage bar, Coverage issues, Overflow hrs, and the Staffing plan\'s short-hour counts, Remaining problems and bottleneck periods; hover text keeps the exact numbers. Unmet patient-hours, coverage %, the solver and the analyses use the exact values.' },
      { term: 'Unmet modeled demand (patient-hours)', body: 'How far demand exceeds modeled capacity, added up hour by hour and area by area. 3 hours short by 2 patients/hr = 6 patient-hours. It is not a count of patients who waited, and not a wait time.' },
      { term: 'Excess capacity', body: 'An hour with a meaningful surplus: capacity exceeds demand by at least 1 patient/hr AND by at least 25% of demand. Smaller surpluses count as "covered".' },
      { term: 'Hidden short', body: 'In a combined view: an hour where the total looks covered, but at least one area is short. Shown with red stripes so good totals can\'t hide local understaffing.' },
      { term: 'Empirical PPH', body: 'Observed patients discharged per attending-hour in the historical data, shown under the sliders for comparison with the assumed ceiling. It reflects past staffing and flow, not necessarily what is achievable.' },
      { term: 'Modeled coverage %', body: 'For each area and hour take the smaller of demand and modeled capacity, add these up, and divide by total demand. 95% = the modeled schedule covers 95% of expected patient-hours — not that 95% of patients were seen on time. Areas are never pooled.' },
    ],
  },
  {
    id: 'colors',
    title: 'Coverage colours',
    intro: 'Used by the coverage bar under the timeline, the week heatmap and the Coverage issues legend.',
    items: [
      { term: 'Short', key: { swatch: STATUS_SWATCH.deficit }, body: 'Demand exceeds modeled capacity by at least 0.05 PPH (smaller shortfalls round to 0.0 and are shown as covered). Darker red = further short.' },
      { term: 'Covered', key: { swatch: STATUS_SWATCH.adequate }, body: 'Capacity meets demand without a meaningful surplus.' },
      { term: 'Excess capacity', key: { swatch: STATUS_SWATCH.excess }, body: 'A meaningful surplus (see Key terms). Darker blue = more surplus.' },
      { term: 'Hidden short (striped)', key: { swatch: STATUS_SWATCH.masked }, body: 'Combined views only: the total is covered but an area underneath is short. Check the area rows / tooltip to see which one.' },
      { term: 'M / F / E letters', body: 'On the week heatmap in combined views: which areas are short in that hour — Main, Fast Track, ERU.' },
    ],
  },
  {
    id: 'stats',
    title: 'Summary numbers (top strip)',
    items: [
      { term: '[Day] attending hrs', body: 'Total attending shift hours on the selected day, all areas.' },
      { term: 'vs baseline', body: 'Change in that day\'s attending hours compared with the loaded schedule. Green = more, red = fewer.' },
      { term: 'Est. extra pts/wk', body: 'A rough indicator only: the selected day\'s change in attending hours × the Main supervision ceiling. Despite the label it is based on the selected day, not the whole week.' },
      { term: 'Overflow hrs', body: 'Hours on the selected day where at least one area is short by 0.05 PPH or more. Hover it for the count per area.' },
      { term: 'Total shifts', body: 'All shifts on the selected day (attendings, residents and PAs).' },
      { term: 'Est. cost / Cost vs baseline', body: 'Shown when Cost modeling is on (⚙ settings). Attending and PA hours × the $/hr rates set above the chart. Residents are not costed.' },
      { term: 'Week attending hrs / vs baseline / shifts', body: 'The same figures summed over all seven days.' },
      { term: 'Yearly hrs (×52)', body: 'Week attending hours × 52.' },
      { term: 'Mon–Sun mini columns', body: 'Each day\'s attending hours (top) and change vs baseline (bottom). The selected day is underlined.' },
    ],
  },
  {
    id: 'timeline',
    title: 'Schedule timeline',
    items: [
      { term: 'Rows and blocks', body: 'Each row is a team; each block is a shift, placed on the hour axis at the top. Shifts that cross midnight wrap back to the start of the same day.' },
      { term: 'Attending', key: { shift: '#2d7a3a', opacity: 1 }, body: 'Solid block.' },
      { term: 'PA', key: { shift: '#2d7a3a', opacity: 0.62 }, body: 'Lighter block.' },
      { term: 'Resident', key: { shift: '#2d7a3a', opacity: 0.42 }, body: 'Faintest block. The label shows the level or role detail.' },
      { term: 'Hover a shift', body: 'Shows its times and how many attendings, PAs and residents that team has on at the hour you are pointing at. Read-only.' },
      { term: 'Click a shift', body: 'Selects it (yellow outline) and opens an editor under it: change start/end times or a resident\'s level. Close with Esc, × or by clicking elsewhere.' },
      { term: 'Move and resize', body: 'Drag a shift to move it (also between teams); drag its left or right edge to change start or end. With a shift selected, ←/→ move it by 30 minutes and Shift+←/→ change its length. The small × deletes it.' },
      { term: 'Team row buttons', body: 'The eye hides/shows a team row (view only — its shifts still count). + adds a shift to that team. Custom teams also have a remove button.' },
      { term: '+ Add team', body: 'Creates a new team. Its "PPH area" decides which area\'s demand and throughput it counts toward.' },
      { term: 'All staff / Attendings only', body: 'Show or hide residents and PAs on the timeline. Hidden shifts still count toward capacity.' },
      { term: 'Copy [day] to…', body: 'Copies the whole day\'s schedule onto other days you pick (undoable).' },
      { term: 'Coverage bar', body: 'The coloured strip under the timeline: one cell per hour, coloured by coverage status for the selected scope (see Coverage colours). Combined scopes show a total row plus one thinner row per area. It updates live while you drag.' },
      { term: '"resolves N, creates M"', body: 'While dragging: how many short hours the move would fix and how many new short hours it would cause.' },
    ],
  },
  {
    id: 'heatmap',
    title: 'Week coverage heatmap',
    intro: 'Under the timeline. Answers "where in the week are we consistently short or overstaffed?" Click the header to open or close it.',
    items: [
      { term: 'Grid', body: 'Rows = days, columns = hours (lined up with the timeline above). Each cell is coloured by coverage status for the selected scope; hover a cell for the exact numbers.' },
      { term: 'Header summary', body: 'Total short hours in the week, and the main hour range that is short on most days.' },
      { term: 'All / area buttons', body: 'Combined scopes only: show the total (All) or one area\'s own coverage.' },
      { term: 'Day labels', body: 'The number next to each day = hours short that day. Click a day to select it.' },
      { term: 'Days short row', body: 'For each hour: on how many of the 7 days it is short. High numbers = a consistent pattern rather than a one-off.' },
      { term: 'Click a cell', body: 'Selects that day and highlights that hour on the timeline and chart.' },
      { term: 'Pattern lines', body: 'Hour ranges short (or with excess) on at least 4 of 7 days, merged into ranges, with the areas driving them.' },
    ],
  },
  {
    id: 'chart',
    title: 'Demand vs capacity chart',
    intro: 'Right-hand panel. The tabs choose the scope (Main, Fast Track, ERU, Main + ERU, Whole ED); the Mean/p50/p75/p90 buttons choose the demand target.',
    items: [
      { term: 'Demand bars', key: { bar: '#38bdf8', opacity: 0.45 }, body: 'Patients per hour starting with the team (roomed), at the chosen target.' },
      { term: 'Mean (reference)', key: { line: '#64748b', dash: 'dotted' }, body: 'Shown when a percentile target is selected, so you can see how much busier the target is than an average day.' },
      { term: '95% band around demand', key: { swatch: 'rgba(56,189,248,0.25)' }, body: 'Uncertainty of the historical average (bootstrap 95% confidence interval). Only for single areas with the Mean target.' },
      { term: 'Proposed cap', key: { line: '#60a5fa', width: 2 }, body: 'Capacity of your current (edited) schedule.' },
      { term: 'Baseline cap', key: { line: '#94a3b8', dash: 'dashed' }, body: 'Capacity of the schedule as loaded.' },
      { term: 'Green / red shading', key: { swatch: 'linear-gradient(90deg, rgba(34,197,94,0.45) 50%, rgba(239,68,68,0.45) 50%)' }, body: 'Between proposed and baseline: green where your edits added capacity, red where they removed it.' },
      { term: 'Empirical cap', key: { line: '#2dd4bf', dash: 'dashed' }, body: 'Attendings on duty × the observed historical rate (Empirical PPH). Residents/PAs are not added separately, because the observed rate already reflects the whole team\'s output per attending-hour.' },
      { term: 'Comparison', key: { line: '#fb923c', dash: 'dashed' }, body: 'Capacity of a saved scenario you selected for comparison.' },
      { term: 'Supervision-limited', key: { dot: '#f59e0b' }, body: 'Dot on the proposed line: attendings are the bottleneck — there are enough residents/PAs, so more attending coverage is what would add capacity.' },
      { term: 'Staffing-limited', key: { dot: '#2dd4bf' }, body: 'Dot on the proposed line: attendings could supervise more, but there aren\'t enough residents/PAs to use it.' },
      { term: 'Component-area deficit', key: { dot: '#ef4444' }, body: 'Combined scopes: at least one area is short that hour, even if the total looks fine.' },
      { term: 'Hover tooltip', body: 'Exact numbers for the hour: demand, each capacity line, the supervision-ceiling vs staffing breakdown, each area\'s net (combined scopes) and each team\'s capacity and limit.' },
      { term: 'Area breakdown line', body: 'Combined scopes, above the chart: capacity minus demand for the total and each area, at the hovered hour (or the day\'s worst hour). ⚠ = the total hides a short area.' },
    ],
  },
  {
    id: 'sliders',
    title: 'Throughput sliders',
    items: [
      { term: 'Attending supervision ceiling / solo throughput', body: 'The assumed attending rates for the selected area(s) (see Key terms). Solo throughput can\'t exceed the ceiling. Changing them changes every capacity number immediately; they are saved with scenarios.' },
      { term: 'Resident / PA max PPH', body: 'Patients per hour each resident level or PA adds under supervision. Fast Track shows its PA solo and with-attending rates.' },
      { term: 'Empirical: x', body: 'The observed historical rate for comparison (see Empirical PPH).' },
      { term: 'Attending / PA $/hr', body: 'Appear when Cost modeling is on. Used only for the cost figures.' },
    ],
  },
  {
    id: 'coverage-issues',
    title: 'Coverage issues list',
    intro: 'Under the chart. Plain-language findings for the selected day and scope, worked out from the same numbers as the chart.',
    items: [
      { term: '▼ short', body: 'An area has a modeled capacity deficit (0.05 PPH or more) over a time range, with its worst hour.' },
      { term: '⚠ hidden short', body: 'Combined scopes: the total is adequate over a time range, but the named area(s) are still below demand.' },
      { term: '▲ excess', body: 'An area has excess capacity over a time range.' },
      { term: 'Ranges', body: 'Consecutive hours with the same issue are merged ("from 17:00–20:00" means 17:00 up to 20:00). Ranges can run past midnight.' },
      { term: 'Hover an item', body: 'Highlights its worst hour on the chart and timeline.' },
    ],
  },
  {
    id: 'tools',
    title: 'Top bar tools',
    items: [
      { term: '↩ / ↪ Undo, redo', body: 'Undo or redo any change, including generated or applied plans. ⌘Z / ⌘⇧Z (Ctrl on Windows).' },
      { term: 'Reset day', body: 'Puts the selected day back to the loaded schedule.' },
      { term: 'Clear day / Clear week', body: 'Empties the day or week completely (asks first; undoable).' },
      { term: '✦ Generate schedule', body: 'Builds a new attending schedule for one area from demand (see Schedule generator).' },
      { term: '▦ Staffing plan', body: 'Answers how many attending hours the ED needs and where they should go: allocate a fixed budget, find the fewest hours for a coverage or unmet-demand target, estimate a minimum practical requirement, or compare a range of budgets (see Staffing plan).' },
      { term: '📊 Scenarios / Save scenario', body: 'Save up to 5 named versions (schedule, sliders, custom teams, target). Click a saved scenario under the chart to draw it as the orange Comparison line; ↩ restores it, × deletes it. The Scenarios panel compares weekly totals. V2 and V3 share one scenario list.' },
      { term: '⚡ Auto-optimize [scope]', body: 'A quick rule-of-thumb patch for the selected day\'s short hours in the selected scope (see Auto-optimize). ▾ → Optimize full week runs it on every day.' },
      { term: '⬇ Export', body: 'Download the current week as CSV or JSON.' },
      { term: '↻ Refresh data', body: 'Re-runs the data pipeline on the server from its raw exports and reloads demand and the schedule. Clears undo history and your unsaved edits. Only shown where the server allows it, and asks for the admin password; on the live site it is normally switched off (data is loaded there by the administrator instead).' },
      { term: '⚙ Settings', body: 'Light/dark theme, and Cost modeling (shows $ estimates using attending and PA hourly rates).' },
      { term: 'v3 badge', body: 'Returns to the version chooser.' },
    ],
  },
  {
    id: 'generator',
    title: 'Schedule generator (✦)',
    intro: 'Suggests an attending schedule for one area from the demand curve. It is a fast heuristic (repeatedly adds the best-value shift, then tidies up), not a proven-best plan.',
    items: [
      { term: 'What it changes', body: 'Replaces that area\'s attending shifts on the chosen days. Residents and PAs stay exactly as they are.' },
      { term: 'How it sizes', body: 'Counts each attending as providing the full supervision ceiling, assuming enough residents/PAs are on their team. Where a team has too few, real capacity (shown by the chart) will be lower than the generator\'s result panel.' },
      { term: 'Hard rules it keeps', body: 'ERU never gets more than one attending at a time (not adjustable), and no attending shift is generated during an area\'s configured closed hours (FastTrack 01:00–07:00). Demand these rules leave uncovered is reported as uncovered, never met by breaking them.' },
      { term: 'Not modelled', body: 'Fast Track solo PA capacity (so it can staff Fast Track more than needed), resident supervision, and the Staffing plan\'s other operational rules. Otherwise only your max/min concurrent limits apply.' },
      { term: 'Shift patterns', body: 'Only the shift start times and lengths you allow are used.' },
      { term: 'Min / max concurrent, overnight min', body: 'How many attendings may or must be on at once; overnight minimum applies 23:00–07:00.' },
      { term: 'Objective', body: 'Either the fewest hours that cover demand, or the best coverage within a weekly hour budget. "Fewest hours" does not guarantee full coverage: Max concurrent can stop it, and the result panel then shows the uncovered patient-hours.' },
      { term: 'Scope: day / templates / week', body: 'Templates = one plan for weekdays (built from Monday), one for Saturday and one for Sunday.' },
      { term: 'Result panel', body: 'Shows hours, shifts and uncovered demand under its own ceiling assumption, cost vs the baseline\'s attending cost, and lets you flip Current/Generated before Accept or Discard.' },
    ],
  },
  {
    id: 'auto-optimize',
    title: 'Auto-optimize (⚡)',
    items: [
      { term: 'What it does', body: 'A rule-of-thumb patch (not an optimizer) for the selected day and scope, area by area: stretches attending shifts ending up to 2 h before a short hour, starts shifts beginning shortly after one up to 2 h earlier, adds a PA where one more PA adds modeled capacity without another attending, adds attending shifts (with a PA alongside when that helps), and as a last resort creates an "Optimized Team". Changes preview on the timeline; Accept or Discard.' },
      { term: 'Rules it never breaks', body: 'Every added or lengthened shift must add modeled capacity (as scheduled). No attending is added where the operational coverage rules forbid one: closed or cross-covered hours, or above an area\'s maximum at once (ERU: one). No staff are added to a closed area. Hours it cannot fix without breaking a rule are listed as "still short" with the reason.' },
      { term: 'What it does not do', body: 'No hour budget, no shift-pattern menu (it can make odd-length shifts), no search for the best plan, and it only adds — it never removes surplus. Review the listed changes before accepting.' },
    ],
  },
  {
    id: 'capacity-views',
    title: 'As scheduled vs operational capacity',
    intro: 'Capacity is counted two ways; each view is labelled. They can differ for the same schedule, and that is expected.',
    items: [
      { term: 'As scheduled', body: 'Everyone counts on the team recorded in the schedule; no area rules. Used by the main chart, coverage bar, week heatmap, Coverage issues, Auto-optimize (for scoring) and the Generator.' },
      { term: 'Operational', body: 'Used by the Staffing plan (its metrics, heatmap, comparisons and "Why deficits remain"). Adds staff routing, the operational coverage rules (dedicated / cross-covered / closed / flexible, ERU at most one attending), cross-coverage, resident supervision, and the no-new-patients cutoffs (Blue from 20:00, FastTrack from midnight, tool-added teams 3 h before their coverage ends).' },
      { term: 'Staff routing (confirmed)', body: 'Confirmed operational rule: FastTrack-team residents/APPs whose role ends in -Green or -Red switch to that Main team at 01:00, when FastTrack closes, and work there until 07:00 (times editable under Operational coverage → Staff operating area). While routed they count only on the Main team, under its supervision rules, and add nothing to FastTrack. The schedule record never changes and patients never move.' },
      { term: 'Example', body: 'Overnight, a FastTrack "EM3/4-Green" resident adds nothing on the main chart (as scheduled: FastTrack has no attending then) but counts on Main Green in the Staffing plan, which also requires Green to have an attending while that resident works.' },
    ],
  },
  {
    id: 'staffing-plan',
    title: 'Staffing plan (▦)',
    intro: 'Answers: "how much attending coverage does this model ask for, and where should it go?" It re-plans attending shifts only, using OPERATIONAL capacity; residents and PAs stay exactly as scheduled — never added, removed or moved. Nothing changes until you click Apply to schedule.',
    items: [
      { term: 'Resident supervision (hard rule)', body: 'A resident on a clinical team (Green, Red, Blue, FastTrack, ERU…) may only work while that team has a supervising attending — checked hour by hour on the team the resident actually works on after staff routing. The planner never leaves such an hour without that team\'s attending; an attending on another team or a planner-added new team does not count. In hours an area is explicitly cross-covered (ERU outside its dedicated window) the covering area\'s attendings supervise, and it must have one on. If an area is set to Flexible with a covering area, the resident\'s team needs its own attending unless the area has no attending at all (then the covering area supervises); an attending on another team of that area never counts. If the hours or rules cannot allow this the plan is refused with the numbers. Residents themselves are never moved, added, removed or re-timed. PAs/APPs are not covered by this rule.' },
      { term: 'No new patients (intake cutoffs)', body: 'A team that closes for the night stops taking NEW patients before it closes, so its patients are finished rather than signed out to Green/Red. Defaults (confirmed): Blue takes no new patients from 20:00 (its shift ends 23:00); FastTrack none from midnight (it closes 01:00); teams added by the planner, Generator or Auto-optimize none in the last 3 hours of their coverage unless another attending continues that team. During those hours the team adds no capacity against demand; its staff still work and its residents still need its attending. Edit them under Operational coverage → No new patients; they are saved with scenarios. Applied in the Staffing plan only — the main chart still counts a team until its shift ends.' },
      { term: 'Fixed attending hours', body: 'At most X attending hours per week (or per year; a year = 52 weeks). Minimises shortfalls — each area-hour\'s shortfall above 2 patients/hr counts 4×, 0.5–2 counts 2×, the first 0.5 counts 1× — then unneeded excess, then hours. Hours that reduce no shortfall are left unallocated.' },
      { term: 'Target modeled coverage', body: 'Three stages: (1) the least unmet demand ANY number of hours could reach under the rules — if the target is beyond it, the result says TARGET INFEASIBLE UNDER CURRENT CONSTRAINTS with the best achievable and no rule is relaxed; (2) the fewest hours meeting the target (optional per-area targets); (3) placement of exactly those hours as in Fixed hours.' },
      { term: 'Maximum modeled unmet demand', body: 'The same three stages with a limit on unmet patient-hours per week instead of a percentage.' },
      { term: 'Minimum practical requirement', body: 'No budget: (1) the least unmet demand any number of hours can reach; (2) a tolerance (default 0.5 coverage points) so tiny modeled gains never justify large hour increases; (3) the fewest hours within it; (4) placement. A modeled figure under the configured assumptions — not required clinical staffing.' },
      { term: 'Resource frontier', body: 'Solves Fixed hours at each budget in a range, each starting from the previous point\'s plan; a point that comes out worse is replaced by the previous plan (marked ↺). Shows unmet demand against hours and the reduction per added hour. The "knee" is a description of the curve, not a recommended budget.' },
      { term: 'Max shortfall per hour', body: 'The fewest hours that keep every area within an allowed shortfall in every hour, then the least excess.' },
      { term: 'Short hours can rise', body: 'The planner minimises the size of shortfalls, not the number of red hours, so a plan can spread a smaller total shortfall over more hours.' },
      { term: 'PAs left without an attending', body: 'Residents always keep their team\'s attending (hard rule). A PA can still be on a team with no attending at some hours; outside FastTrack\'s solo PA rate their modeled capacity is then zero. Check "Unsupervised resident/PA h" and "No attending, demand".' },
      { term: 'Why deficits remain', body: 'Labels per remaining short hour (several can apply). Attending-limited: another attending is allowed, adds capacity, and a permitted shift would put at least half of it against unmet demand. Resident/APP-limited: one more PA would add capacity without another attending (diagnostic only — never added). Operational-rule-limited: closed, cross-covered, ERU already has one, or every team is at its limit. Shift-structure-limited: no permitted shift fits, or the best one would mostly add surplus. Little modeled benefit: neither another attending nor another PA adds modeled capacity.' },
      { term: 'Solver status', body: '"Optimal" = mathematically proven best plan for this model (zero gap). "Near-optimal — within X%" = the search stopped inside its 0.1% tolerance of the best possible objective, so it is not proven best. "Best found — X% optimality gap" = the search budget ran out first. None of these says anything about real-world correctness.' },
      { term: 'Repeatable', body: 'The same inputs give the same plan on any computer: the search stops on a fixed amount of work (Quick / Standard / Thorough), not a stopwatch. Exception: a run that hits the 2-minute safety limit. Frontier points also depend on which budgets are listed.' },
      { term: 'OBSERVED / CONFIGURED / ASSUMED / CALCULATED', body: 'Tags on every result: from data, chosen by you, a model assumption, or model/solver output.' },
      { term: 'Planning units', body: 'Optional clinical hours per FTE and an hourly rate turn hours into approximate FTE and an illustrative cost. Nothing is assumed until you enter them; cost is not institutional cost.' },
      { term: 'Shift times and lengths', body: 'Which shifts the planner may use. "Current start times" is today\'s structure; "Any hour" is an expanded structure for testing whether timing, rather than hours, limits coverage. Larger menus can end with slightly worse plans within the same search effort.' },
      { term: 'Additional simultaneous attendings', body: 'How many attendings the planner may add per area on new teams, beyond one per existing team — so it can add attending coverage at peaks, not only re-time today\'s shifts. ERU stays at one.' },
      { term: 'Operational coverage', body: 'Hard attending-coverage rules per area, day and time, applied before any optimization (on by default). Dedicated (hard): the area must have its own attending. The default ERU windows copy today\'s ERU dedicated coverage for comparison; they are not a clinically established minimum. Cross-covered: no dedicated attending; another area\'s attendings are responsible. Closed: no attending placed, but historical demand recorded then still counts. Flexible: the planner decides. If the budget cannot cover the hard rules, the plan is refused with the numbers.' },
      { term: 'At most one ERU attending', body: 'ERU never has more than one dedicated attending at the same time, in any scenario — also enforced by Auto-optimize. Remaining ERU shortfall is shown rather than adding a second ERU attending.' },
      { term: 'Cross-coverage', body: 'Responsibility, supervision and throughput are kept apart. The covered area keeps its own demand; the covering attendings are responsible for it and supervise its residents/PAs. The covering area\'s own demand is counted first; only its leftover ceiling can be credited. How much that adds is uncertain, so it is an explicit assumption: Conservative (default) credits none, so the covered area\'s demand counts as unmet; Ceiling ratio converts the leftover at 0.8/2.1, capped at the covered area\'s supervised resident/PA capacity (unvalidated — for comparison only); Custom uses values you set.' },
      { term: 'Settings you can change', body: 'Everything that may change is editable, and saved with scenarios: the schedule (timeline), throughput rates (sliders), each area\'s coverage rules and ERU window, staff routing rules and times, and the no-new-patients cutoffs (Staffing plan → Operational coverage). The resident-supervision rule and the ERU one-attending maximum are fixed rules.' },
      { term: 'Staff operating area', body: 'Where a resident or PA works at a given time, separate from the team recorded in the schedule (see As scheduled vs operational). The default FastTrack → Main overnight routing is a confirmed operational rule.' },
      { term: 'ERU dedicated coverage scenario', body: 'Pick when ERU has its own attending (Current, Core daytime, Extended evening, 24/7, or a custom window); the planner then places the rest of the budget and, if ticked, also solves Current ERU coverage with the same budget for comparison. Windows that 8/10/12-hour shifts cannot cover without two ERU attendings at once are refused. Scenarios are comparisons, not recommendations.' },
      { term: 'Minimum attending coverage', body: 'Hard rules such as "ERU needs at least 1 attending 08:00–20:00". Without them the planner may leave a low-throughput area unattended if hours do more good elsewhere.' },
      { term: 'Locked shifts', body: 'Keep today\'s shifts that start within a time window exactly as they are; their hours count toward the budget.' },
      { term: 'Coverage improvement table', body: 'Today → proposed, per area. The "(pooled)" row adds areas together and is for reference only, because pooling can hide a short area. Short-hour counts use the same 0.05 PPH display rule as the heatmap; uncovered patient-hours are exact.' },
      { term: 'No attending, demand', body: 'Hours where patients are expected but the area has no attending at all and no cross-coverage. The link beside it adds a minimum-coverage rule and re-runs.' },
      { term: 'Apply / Save as scenario', body: 'Apply to schedule replaces the week in one undoable step. Save as scenario keeps the plan without changing the schedule and shows it as the chart\'s Comparison line.' },
    ],
  },
  {
    id: 'limits',
    title: 'Model assumptions and limits',
    items: [
      { term: 'Decision support, not a requirement', body: 'Coverage and recommendations come from a model. They have not been validated as clinical staffing requirements; review them with the people who run the department.' },
      { term: 'Throughput numbers are assumptions', body: 'Ceilings, solo throughput and resident/PA rates are chosen values, not measurements; solo attending throughput cannot be estimated from this data. In today\'s schedule most Main team-hours sit at the ceiling, so the Main ceiling drives many results.' },
      { term: 'Demand is historical roomed patients', body: 'Patients per hour by the hour they were roomed with each area\'s team, by day of week, as an average or per-hour percentile. The model does not simulate queues, so it cannot say how long anyone would wait, and random surges beyond the chosen percentile are not planned for.' },
      { term: 'Acuity and resuscitation', body: 'How sick patients are, resuscitations and critical-care time are not modeled. Dedicated ERU coverage also provides readiness the model does not value.' },
      { term: 'Boarding', body: 'Admitted patients waiting for a bed, and the space and staff time they take, are not modeled.' },
      { term: 'Procedures, documentation, teaching', body: 'Procedures, charting, handoffs and supervising/teaching residents are not modeled separately; they are only implicit in the assumed rates.' },
      { term: 'Flow outcomes', body: 'Door-to-provider time, length of stay and left-without-being-seen are not used. Unmet modeled demand is none of these.' },
      { term: 'Cross-cover productivity', body: 'How many covered-area patients the covering attendings can take on is unknown. The default credits none; the ceiling-ratio option is unvalidated. Cross-cover is modeled only in the Staffing plan.' },
      { term: 'One day template per weekday', body: 'Each day is planned as a 24-hour template; an overnight shift wraps into the early hours of the same day.' },
      { term: 'Also not modelled', body: 'Fatigue, breaks, skill mix within a level, unit geography, and patient re-routing between areas (e.g. extending FastTrack hours).' },
    ],
  },
]

export const HELP_SECTION_IDS = HELP_SECTIONS.map(s => s.id)
