// In-app help for V3: what every non-obvious number, colour, line and
// button means. Edit wording here; the Help panel only renders it.
//
// Each section: { id, title, intro?, items: [{ term, body, key? }] }
// `key` draws a small visual sample next to the term:
//   { swatch: css-background }            a coloured box
//   { line: color, dash?: 'dashed'|'dotted', width? }
//   { dot: color }                        a chart marker
//   { bar: color, opacity? }              a demand bar
//   { shift: color, opacity }             a shift block
// Sections with an `id` can be opened directly by the small ? buttons.

import { STATUS_SWATCH } from '../components/coverageStyles'

export const HELP_SECTIONS = [
  {
    id: 'start',
    title: 'Start here',
    intro: 'This tool compares staffing against how many patients historically arrive each hour, area by area, and helps you try out different schedules.',
    items: [
      { term: 'The core idea', body: 'For every hour, the tool estimates how many patients per hour the scheduled staff can handle (capacity) and compares it with how many typically arrive (demand). Capacity below demand = the area is short that hour.' },
      { term: 'Layout', body: 'Top bar: tools. Below it: day tabs and summary numbers. Left: the day\'s schedule as a timeline, with a coverage bar and the week heatmap underneath. Right: the demand-vs-capacity chart for the selected area.' },
      { term: 'Nothing is saved automatically', body: 'Edits change your working copy in this browser session. Use Save scenario to keep a version, Export to download it, or Reset day to go back to the loaded schedule. Undo (⌘Z / Ctrl+Z) works for every change.' },
      { term: 'Areas are separate', body: 'Main, Fast Track and ERU each have their own demand and staff. Spare capacity in one area never covers a shortfall in another — this matters in the combined views (Main + ERU, Whole ED).' },
      { term: 'These are estimates', body: 'Capacity comes from assumed throughput numbers (see Key terms and Model assumptions). Treat every number here as decision support to discuss, not as a validated staffing requirement.' },
      { term: 'Quick tour', body: '1) Pick an area tab on the chart. 2) Look for red on the coverage bar and heatmap. 3) Drag or click shifts to adjust. 4) Watch the chart and "Coverage issues" update. 5) Save the result as a scenario to compare.' },
      { term: 'Opening this help', body: 'Click ❓ Help in the top bar, press the ? key, or click any small ? next to a part of the screen to jump straight to its explanation.' },
    ],
  },
  {
    id: 'glossary',
    title: 'Key terms',
    items: [
      { term: 'PPH (patients per hour)', body: 'The unit used everywhere: how many patients arrive per hour (demand), or how many a clinician or team can handle per hour (capacity).' },
      { term: 'Demand', body: 'Historical arrivals per hour for each area and day of the week, from the encounter data.' },
      { term: 'Demand target — Mean / p50 / p75 / p90', body: 'Which version of historical demand to plan against. Mean = the average day. p50 = a typical (median) day. p75 / p90 = busier days: demand at that hour is at or below this on 75% / 90% of days. Planning to p90 staffs for busy days and shows more shortfalls. Percentile buttons are greyed out until the data pipeline has computed them.' },
      { term: 'Capacity', body: 'Patients per hour the scheduled staff can handle, calculated per team and then added up for the area.' },
      { term: 'Supervision ceiling (attending PPH)', body: 'The most patients per hour one attending can be responsible for, including patients seen by the residents/PAs they supervise. A team can never exceed this, however many residents it has. Defaults: Main 2.1, Fast Track 3.5, ERU 0.8.' },
      { term: 'Solo throughput', body: 'Patients per hour an attending sees personally when working alone. A team\'s capacity = the smaller of (ceiling) and (solo throughput + residents/PAs), so residents/PAs lift an attending up toward the ceiling but not past it.' },
      { term: 'Resident / PA PPH', body: 'Patients per hour each resident (by level: PGY-1 to PGY-4, Off-Service) or PA adds under supervision. Residents and supervised PAs count for nothing when no attending is on their team.' },
      { term: 'Fast Track PA (solo / with attending)', body: 'Fast Track PAs see patients on their own (solo rate) even with no attending on, plus a separate rate for patients co-managed with an attending. Solo PA capacity is added on top of the ceiling.' },
      { term: 'Team', body: 'One attending\'s group with its residents/PAs (e.g. Green, Red, Blue in Main). Capacity is calculated team by team; residents on one team never help another team\'s attending.' },
      { term: 'Area and scope', body: 'An area is Main, Fast Track or ERU. A scope is what you are looking at: one area, Main + ERU, or Whole ED. Combined scopes add the areas together but always keep each area\'s own result visible.' },
      { term: 'Baseline vs proposed', body: 'Baseline = the schedule as loaded from the database. Proposed = your current edited version. "vs baseline" numbers show the difference.' },
      { term: 'Short (deficit)', body: 'An hour where demand is higher than capacity.' },
      { term: 'Unmet demand (patient-hours)', body: 'How far demand exceeds capacity, added up over hours. 3 hours short by 2 patients/hr = 6 patient-hours unmet.' },
      { term: 'Excess capacity', body: 'An hour with a meaningful surplus: capacity exceeds demand by at least 1 patient/hr AND by at least 25% of demand. Smaller surpluses count as "covered".' },
      { term: 'Hidden short', body: 'In a combined view: an hour where the total looks covered, but at least one area is short. Shown with red stripes so good totals can\'t hide local understaffing.' },
      { term: 'Empirical PPH', body: 'Observed patients discharged per attending-hour in the historical data, shown under the sliders for comparison with the assumed ceiling. It reflects past staffing and flow, not necessarily what is achievable.' },
      { term: 'Coverage %', body: 'Share of demand that capacity can handle: demand met ÷ total demand, counted area by area.' },
    ],
  },
  {
    id: 'colors',
    title: 'Coverage colours',
    intro: 'Used by the coverage bar under the timeline, the week heatmap and the Coverage issues legend.',
    items: [
      { term: 'Short', key: { swatch: STATUS_SWATCH.deficit }, body: 'Demand exceeds capacity. Darker red = further short.' },
      { term: 'Covered', key: { swatch: STATUS_SWATCH.adequate }, body: 'Capacity meets demand without a meaningful surplus.' },
      { term: 'Excess capacity', key: { swatch: STATUS_SWATCH.excess }, body: 'A meaningful surplus (see Key terms). Darker blue = more surplus.' },
      { term: 'Hidden short (striped)', key: { swatch: STATUS_SWATCH.masked }, body: 'Combined views only: the total is covered but an area underneath is short. Check the area rows / tooltip to see which one.' },
      { term: 'M / F / E letters', body: 'On the week heatmap in combined views: which areas are short in that hour — Main, Fast Track, ERU.' },
    ],
  },
  {
    id: 'stats',
    title: 'Summary numbers (top strip)',
    items: [
      { term: '[Day] attending hrs', body: 'Total attending shift hours on the selected day, all areas.' },
      { term: 'vs baseline', body: 'Change in that day\'s attending hours compared with the loaded schedule. Green = more, red = fewer.' },
      { term: 'Est. extra pts/wk', body: 'A rough indicator only: the selected day\'s change in attending hours × the Main supervision ceiling. Despite the label it is based on the selected day, not the whole week.' },
      { term: 'Overflow hrs', body: 'Hours on the selected day where at least one area is short. Hover it for the count per area.' },
      { term: 'Total shifts', body: 'All shifts on the selected day (attendings, residents and PAs).' },
      { term: 'Est. cost / Cost vs baseline', body: 'Shown when Cost modeling is on (⚙ settings). Attending and PA hours × the $/hr rates set above the chart. Residents are not costed.' },
      { term: 'Week attending hrs / vs baseline / shifts', body: 'The same figures summed over all seven days.' },
      { term: 'Yearly hrs (×52)', body: 'Week attending hours × 52.' },
      { term: 'Mon–Sun mini columns', body: 'Each day\'s attending hours (top) and change vs baseline (bottom). The selected day is underlined.' },
    ],
  },
  {
    id: 'timeline',
    title: 'Schedule timeline',
    items: [
      { term: 'Rows and blocks', body: 'Each row is a team; each block is a shift, placed on the hour axis at the top. Shifts that cross midnight wrap back to the start of the same day.' },
      { term: 'Attending', key: { shift: '#2d7a3a', opacity: 1 }, body: 'Solid block.' },
      { term: 'PA', key: { shift: '#2d7a3a', opacity: 0.62 }, body: 'Lighter block.' },
      { term: 'Resident', key: { shift: '#2d7a3a', opacity: 0.42 }, body: 'Faintest block. The label shows the level or role detail.' },
      { term: 'Hover a shift', body: 'Shows its times and how many attendings, PAs and residents that team has on at the hour you are pointing at. Read-only.' },
      { term: 'Click a shift', body: 'Selects it (yellow outline) and opens an editor under it: change start/end times or a resident\'s level. Close with Esc, × or by clicking elsewhere.' },
      { term: 'Move and resize', body: 'Drag a shift to move it (also between teams); drag its left or right edge to change start or end. With a shift selected, ←/→ move it by 30 minutes and Shift+←/→ change its length. The small × deletes it.' },
      { term: 'Team row buttons', body: 'The eye hides/shows a team row (view only — its shifts still count). + adds a shift to that team. Custom teams also have a remove button.' },
      { term: '+ Add team', body: 'Creates a new team. Its "PPH area" decides which area\'s demand and throughput it counts toward.' },
      { term: 'All staff / Attendings only', body: 'Show or hide residents and PAs on the timeline. Hidden shifts still count toward capacity.' },
      { term: 'Copy [day] to…', body: 'Copies the whole day\'s schedule onto other days you pick (undoable).' },
      { term: 'Coverage bar', body: 'The coloured strip under the timeline: one cell per hour, coloured by coverage status for the selected scope (see Coverage colours). Combined scopes show a total row plus one thinner row per area. It updates live while you drag.' },
      { term: '"resolves N, creates M"', body: 'While dragging: how many short hours the move would fix and how many new short hours it would cause.' },
    ],
  },
  {
    id: 'heatmap',
    title: 'Week coverage heatmap',
    intro: 'Under the timeline. Answers "where in the week are we consistently short or overstaffed?" Click the header to open or close it.',
    items: [
      { term: 'Grid', body: 'Rows = days, columns = hours (lined up with the timeline above). Each cell is coloured by coverage status for the selected scope; hover a cell for the exact numbers.' },
      { term: 'Header summary', body: 'Total short hours in the week, and the main hour range that is short on most days.' },
      { term: 'All / area buttons', body: 'Combined scopes only: show the total (All) or one area\'s own coverage.' },
      { term: 'Day labels', body: 'The number next to each day = hours short that day. Click a day to select it.' },
      { term: 'Days short row', body: 'For each hour: on how many of the 7 days it is short. High numbers = a consistent pattern rather than a one-off.' },
      { term: 'Click a cell', body: 'Selects that day and highlights that hour on the timeline and chart.' },
      { term: 'Pattern lines', body: 'Hour ranges short (or with excess) on at least 4 of 7 days, merged into ranges, with the areas driving them.' },
    ],
  },
  {
    id: 'chart',
    title: 'Demand vs capacity chart',
    intro: 'Right-hand panel. The tabs choose the scope (Main, Fast Track, ERU, Main + ERU, Whole ED); the Mean/p50/p75/p90 buttons choose the demand target.',
    items: [
      { term: 'Demand bars', key: { bar: '#38bdf8', opacity: 0.45 }, body: 'Patients per hour arriving at the chosen target.' },
      { term: 'Mean (reference)', key: { line: '#64748b', dash: 'dotted' }, body: 'Shown when a percentile target is selected, so you can see how much busier the target is than an average day.' },
      { term: '95% band around demand', key: { swatch: 'rgba(56,189,248,0.25)' }, body: 'Uncertainty of the historical average (bootstrap 95% confidence interval). Only for single areas with the Mean target.' },
      { term: 'Proposed cap', key: { line: '#60a5fa', width: 2 }, body: 'Capacity of your current (edited) schedule.' },
      { term: 'Baseline cap', key: { line: '#94a3b8', dash: 'dashed' }, body: 'Capacity of the schedule as loaded.' },
      { term: 'Green / red shading', key: { swatch: 'linear-gradient(90deg, rgba(34,197,94,0.45) 50%, rgba(239,68,68,0.45) 50%)' }, body: 'Between proposed and baseline: green where your edits added capacity, red where they removed it.' },
      { term: 'Empirical cap', key: { line: '#2dd4bf', dash: 'dashed' }, body: 'Attendings on duty × the observed historical rate (Empirical PPH). Residents/PAs are not added separately, because the observed rate already reflects the whole team\'s output per attending-hour.' },
      { term: 'Comparison', key: { line: '#fb923c', dash: 'dashed' }, body: 'Capacity of a saved scenario you selected for comparison.' },
      { term: 'Supervision-limited', key: { dot: '#f59e0b' }, body: 'Dot on the proposed line: attendings are the bottleneck — there are enough residents/PAs, so more attending coverage is what would add capacity.' },
      { term: 'Staffing-limited', key: { dot: '#2dd4bf' }, body: 'Dot on the proposed line: attendings could supervise more, but there aren\'t enough residents/PAs to use it.' },
      { term: 'Component-area deficit', key: { dot: '#ef4444' }, body: 'Combined scopes: at least one area is short that hour, even if the total looks fine.' },
      { term: 'Hover tooltip', body: 'Exact numbers for the hour: demand, each capacity line, the supervision-ceiling vs staffing breakdown, each area\'s net (combined scopes) and each team\'s capacity and limit.' },
      { term: 'Area breakdown line', body: 'Combined scopes, above the chart: capacity minus demand for the total and each area, at the hovered hour (or the day\'s worst hour). ⚠ = the total hides a short area.' },
    ],
  },
  {
    id: 'sliders',
    title: 'Throughput sliders',
    items: [
      { term: 'Attending supervision ceiling / solo throughput', body: 'The assumed attending rates for the selected area(s) (see Key terms). Solo throughput can\'t exceed the ceiling. Changing them changes every capacity number immediately; they are saved with scenarios.' },
      { term: 'Resident / PA max PPH', body: 'Patients per hour each resident level or PA adds under supervision. Fast Track shows its PA solo and with-attending rates.' },
      { term: 'Empirical: x', body: 'The observed historical rate for comparison (see Empirical PPH).' },
      { term: 'Attending / PA $/hr', body: 'Appear when Cost modeling is on. Used only for the cost figures.' },
    ],
  },
  {
    id: 'coverage-issues',
    title: 'Coverage issues list',
    intro: 'Under the chart. Plain-language findings for the selected day and scope, worked out from the same numbers as the chart.',
    items: [
      { term: '▼ short', body: 'An area has a capacity deficit over a time range, with its worst hour.' },
      { term: '⚠ hidden short', body: 'Combined scopes: the total is adequate over a time range, but the named area(s) are still below demand.' },
      { term: '▲ excess', body: 'An area has excess capacity over a time range.' },
      { term: 'Ranges', body: 'Consecutive hours with the same issue are merged ("from 17:00–20:00" means 17:00 up to 20:00). Ranges can run past midnight.' },
      { term: 'Hover an item', body: 'Highlights its worst hour on the chart and timeline.' },
    ],
  },
  {
    id: 'tools',
    title: 'Top bar tools',
    items: [
      { term: '↩ / ↪ Undo, redo', body: 'Undo or redo any change, including generated or applied plans. ⌘Z / ⌘⇧Z (Ctrl on Windows).' },
      { term: 'Reset day', body: 'Puts the selected day back to the loaded schedule.' },
      { term: 'Clear day / Clear week', body: 'Empties the day or week completely (asks first; undoable).' },
      { term: '✦ Generate schedule', body: 'Builds a new attending schedule for one area from demand (see Schedule generator).' },
      { term: '▦ Staffing plan', body: 'Spreads a budget of attending hours across areas, days and times (see Staffing plan).' },
      { term: '📊 Scenarios / Save scenario', body: 'Save up to 5 named versions (schedule, sliders, custom teams, target). Click a saved scenario under the chart to draw it as the orange Comparison line; ↩ restores it, × deletes it. The Scenarios panel compares weekly totals. V2 and V3 share one scenario list.' },
      { term: '⚡ Auto-optimize [scope]', body: 'Tries to fix the selected day\'s short hours in the selected scope by adjusting the existing schedule (see Auto-optimize). ▾ → Optimize full week runs it on every day.' },
      { term: '⬇ Export', body: 'Download the current week as CSV or JSON.' },
      { term: '↻ Refresh data', body: 'Re-runs the data pipeline on the server and reloads demand and the schedule. Clears undo history and your unsaved edits.' },
      { term: '⚙ Settings', body: 'Light/dark theme, and Cost modeling (shows $ estimates using attending and PA hourly rates).' },
      { term: 'v3 badge', body: 'Returns to the version chooser.' },
    ],
  },
  {
    id: 'generator',
    title: 'Schedule generator (✦)',
    intro: 'Designs an attending schedule for one area from the demand curve.',
    items: [
      { term: 'What it changes', body: 'Replaces that area\'s attending shifts on the chosen days. Residents and PAs stay exactly as they are.' },
      { term: 'How it sizes', body: 'Counts each attending as providing the full supervision ceiling, assuming enough residents/PAs are on their team. Where a team has too few, real capacity (shown by the chart) will be lower than the generator\'s result panel.' },
      { term: 'As scheduled vs operational', body: 'The main chart and heatmap show capacity AS SCHEDULED: everyone counted on the team recorded in the schedule — the same basis as the editor\'s auto-optimize and generator. The Staffing Plan (its metrics, heatmap, comparisons and reports) uses OPERATIONAL capacity: staff operating areas, area closures, cross-coverage and its throughput assumption. Each view is labelled.' },
      { term: 'Not modelled', body: 'Fast Track solo PA capacity — so it can staff Fast Track more than needed.' },
      { term: 'Shift patterns', body: 'Only the shift start times and lengths you allow are used.' },
      { term: 'Min / max concurrent, overnight min', body: 'How many attendings may or must be on at once; overnight minimum applies 23:00–07:00.' },
      { term: 'Objective', body: 'Either the fewest hours that cover demand, or the best coverage within a weekly hour budget.' },
      { term: 'Scope: day / templates / week', body: 'Templates = one plan for weekdays (built from Monday), one for Saturday and one for Sunday.' },
      { term: 'Result panel', body: 'Shows hours, shifts and uncovered demand under its own ceiling assumption, cost vs the baseline\'s attending cost, and lets you flip Current/Generated before Accept or Discard.' },
    ],
  },
  {
    id: 'auto-optimize',
    title: 'Auto-optimize (⚡)',
    items: [
      { term: 'What it does', body: 'For the selected day and scope, works through short hours area by area: extends or moves nearby attending shifts, adds PAs where residents/PAs are the bottleneck, adds attending shifts, and as a last resort creates an "Optimized Team".' },
      { term: 'What it does not do', body: 'It has no hour budget and no shift-pattern menu, and it only adds or moves coverage — it never removes surplus. Review the listed changes before accepting.' },
    ],
  },
  {
    id: 'staffing-plan',
    title: 'Staffing plan (▦)',
    intro: 'Answers: "how much attending coverage does this ED need, and where should it go?" It re-plans attending shifts in the chosen scope; residents and PAs stay exactly where they are — never added, removed or moved. Nothing changes until you click Apply.',
    items: [
      { term: 'Fixed attending hours', body: 'Attending hours per year or per week (a year = 52 weeks, not rounded) — a maximum. Defaults to today\'s hours for the scope. The planner answers where those hours should go.' },
      { term: 'Target modeled coverage', body: 'The fewest attending hours that reach a modeled coverage target (served ÷ demand, per area-hour), with optional per-area minimums. If no number of hours can reach it under the rules, team limits and shift menu, the result says TARGET INFEASIBLE UNDER CURRENT CONSTRAINTS and shows the best achievable coverage and what limits it — no rule is relaxed.' },
      { term: 'Maximum modeled unmet demand', body: 'The fewest attending hours keeping modeled unmet demand at or below a number of patient-hours per week.' },
      { term: 'Minimum practical requirement', body: 'No budget. First finds the least unmet demand any number of hours can reach (100% is not assumed possible), then the fewest hours within a tolerance of it (so tiny modeled gains never justify large hour increases), then places them. A minimum practical MODELED requirement under the configured assumptions — not required clinical staffing.' },
      { term: 'Resource frontier', body: 'Solves a series of budgets and shows modeled unmet demand (or coverage) against attending hours, with the marginal reduction per added attending-hour. Each point starts from the previous plan and is never shown worse than it. A "knee" is a description of the curve, not a recommended budget. Click a row to open that plan.' },
      { term: 'Why deficits remain', body: 'For every short hour: attending-limited (another attending fits and a permitted shift would mostly meet demand), resident/APP-limited (an attending has supervision headroom — one more PA would help; shown for information, never added), operational-rule-limited (closed, cross-covered, ERU max one, team limits), shift-structure-limited (no permitted shift uses the extra capacity well). An hour can have several.' },
      { term: 'OBSERVED / CONFIGURED / ASSUMED / CALCULATED', body: 'Tags on every result: from data, chosen by you, a model assumption, or solver/model output.' },
      { term: 'Planning units', body: 'Optional clinical hours per FTE and an hourly rate turn hours into approximate FTE and an illustrative cost. Nothing is assumed until you enter them; cost is not institutional cost.' },
      { term: 'Max shortfall per hour', body: 'The planner\'s original estimate mode: the fewest hours that keep every area within an allowed shortfall in every hour.' },
      { term: 'Shift times and lengths', body: 'Which shifts the planner may use. "Current start times" is today\'s structure; "Any hour" is an expanded structure for testing whether timing, rather than hours, limits coverage. Larger menus can end with slightly worse plans within the same search effort.' },
      { term: 'Additional simultaneous attendings', body: 'How many attendings the planner may add per area on new teams, beyond one per existing team — so it can add attending coverage at peaks, not only re-time today\'s shifts. ERU stays at one.' },
      { term: 'Operational coverage', body: 'Hard attending-coverage rules per area, day and time, applied before any optimization. Dedicated (hard): the area must have its own attending — the planner cannot move those hours elsewhere. The default ERU windows are today\'s ERU dedicated coverage, kept so alternatives can be compared against it; they are not a clinically established minimum. Cross-covered: no dedicated attending; another area\'s attendings are responsible (ERU by Main outside its dedicated hours). Closed: no attending placed, but any historical demand recorded then still counts. Flexible: the planner decides. If the budget cannot cover the hard rules, the plan is refused with the numbers.' },
      { term: 'At most one ERU attending', body: 'ERU never has more than one dedicated attending at the same time, in any scenario. If ERU demand exceeds what one attending and team can handle, the remaining shortfall is shown rather than adding a second ERU attending.' },
      { term: 'Cross-coverage', body: 'Responsibility, supervision and throughput are kept apart. The covered area keeps its own demand; the covering attendings are responsible for it and supervise its residents/PAs. How much modeled throughput that adds is uncertain, so it is an explicit assumption: Conservative (default) credits none; Ceiling ratio credits the covering attendings\' spare capacity × 0.8/2.1 (unvalidated — for comparison only); Custom uses values you set.' },
      { term: 'Staff operating area', body: 'Where a resident or PA actually works at a given time, separate from the team recorded in the schedule. Default: FastTrack-team residents/PAs whose role ends in -Green or -Red work that Main team while FastTrack is closed (01:00–07:00) — inferred from the schedule and marked unconfirmed until the department confirms. The schedule record never changes, and patients never move.' },
      { term: 'ERU dedicated coverage scenario', body: 'Pick when ERU has its own attending (Current, Core daytime, Extended evening, 24/7, or a custom window); the planner then places the rest of the budget and, if ticked, also solves Current ERU coverage with the same budget so you can see where hours moved and what changed. Windows that 8/10/12-hour shifts cannot cover without two ERU attendings at once (e.g. a 14-hour window) are refused. Scenarios are comparisons, not recommendations.' },
      { term: 'Minimum attending coverage', body: 'Hard rules such as "ERU needs at least 1 attending 08:00–20:00". Without them the planner may leave a low-throughput area unattended if hours do more good elsewhere.' },
      { term: 'Locked shifts', body: 'Keep today\'s shifts that start within a time window exactly as they are; their hours count toward the budget.' },
      { term: 'Search: Quick / Standard / Thorough', body: 'How long the solver searches. Results are always repeatable for the same inputs.' },
      { term: 'How it decides', body: 'Minimises shortfalls area by area — severe shortfalls (over 2 patients/hr) cost most — then unnecessary excess, then hours used. One area\'s surplus never offsets another\'s shortfall.' },
      { term: 'Solver tile', body: '"Optimal" = proven best for the model. "Best found … within X%" = the plan is guaranteed to be within X% of the best possible.' },
      { term: 'Coverage improvement table', body: 'Today → proposed, per area. The "(pooled)" row adds areas together and is for reference only, because pooling can hide a short area.' },
      { term: 'No attending, demand', body: 'Hours where patients are expected but the area has no attending at all. The link beside it adds a minimum-coverage rule and re-runs.' },
      { term: 'Apply / Save as scenario', body: 'Apply replaces the week in one undoable step. Save as scenario keeps the plan without changing the schedule and shows it as the chart\'s Comparison line.' },
    ],
  },
  {
    id: 'limits',
    title: 'Model assumptions and limits',
    items: [
      { term: 'Decision support, not a requirement', body: 'Coverage and recommendations come from a model. They have not been validated as clinical staffing requirements; review them with the people who run the department.' },
      { term: 'Throughput numbers are assumptions', body: 'Ceilings, solo throughput and resident/PA rates are chosen values, not measurements. In today\'s schedule most Main team-hours sit at the ceiling, so the Main ceiling drives many results.' },
      { term: 'Demand is historical', body: 'Hourly arrivals by day of week from past data. It does not include acuity, boarding, or length of stay.' },
      { term: 'One day template per weekday', body: 'Each day is planned as a 24-hour template; an overnight shift wraps into the early hours of the same day.' },
      { term: 'Not modelled', body: 'Handoffs, fatigue, skill mix, breaks, unit geography, acuity, and patient re-routing between areas (e.g. extending FastTrack hours). Cross-cover is modelled only as supervision headroom (see Staffing plan → Cross-coverage), and only in the staffing planner.' },
    ],
  },
]

export const HELP_SECTION_IDS = HELP_SECTIONS.map(s => s.id)
